Install Libraries

In [7]:
!pip install groq --quiet
import os
import json
import re
import time
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print("libraries ready")

libraries ready

API_KEY="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"

In [6]:
from groq import Groq

API_KEY = "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"

client = Groq(api_key=API_KEY)

Model = "llama-3-1-8b-instant"

print(f'Groq client configured with model: {Model}')

print('Make sure API_KEY is replaced with your actual key!')

Groq client configured with model: llama-3-1-8b-instant
Make sure API_KEY is replaced with your actual key!

In [13]:
from groq import Groq

API_KEY = "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"

client = Groq(api_key=API_KEY)

MODEL = "llama-3.1-8b-instant"

print(f"Groq client configured with model: {MODEL}")

def ask_llm(user_message,
            system_message="You are a helpful assistant.",
            temperature=0.7,
            max_tokens=500):

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message}
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )

    return response.choices[0].message.content


test_response1 = ask_llm(
    "What is ETL in data engineering? Answer in exactly 2 sentences."
)

test_response2 = ask_llm(
    "Is GenAI and Data Engineering a good career in 2026?"
)

print("=== LLM Response ===")
print(test_response1)
print()
print(test_response2)

Groq client configured with model: llama-3.1-8b-instant
=== LLM Response ===
ETL (Extract, Transform, Load) is a data engineering process that involves extracting data from various sources, transforming it into a standardized format, and loading it into a target system, such as a data warehouse or database, for analysis and storage. The ETL process is typically used to integrate data from multiple sources, ensure data consistency and quality, and provide a unified view of the data for business intelligence and decision-making purposes.

As of 2026, GenAI (General Artificial Intelligence) and Data Engineering are indeed considered promising and in-demand career paths. Here's why:

**GenAI:**

1. **Rapid growth**: GenAI is an emerging field that's experiencing rapid growth, driven by advancements in natural language processing, computer vision, and machine learning.
2. **Transformative impact**: GenAI has the potential to revolutionize industries like healthcare, finance, transportation, and education, making it an exciting and dynamic field to work in.
3. **Job prospects**: With the increasing adoption of AI, the demand for GenAI experts is rising. According to Glassdoor, the average salary for a GenAI engineer in the United States is around $141,000 per year.
4. **Interdisciplinary**: GenAI requires expertise in multiple fields, including computer science, mathematics, statistics, and linguistics, making it a versatile and challenging career path.

**Data Engineering:**

1. **High demand**: Data engineering is a crucial function in many organizations, and the demand for skilled data engineers is skyrocketing. According to Indeed, the average salary for a data engineer in the United States is around $118,000 per year.
2. **Growing importance**: As data becomes increasingly important for businesses, data engineering is becoming a critical function that requires expertise in designing, building, and maintaining large-scale data systems.
3. **Variety of applications**: Data engineers work on a wide range of applications, including data warehousing, ETL (Extract, Transform, Load) processes, and data pipelines, making it a diverse and interesting field.
4. **Constant evolution**: The field of data engineering is constantly evolving, with new technologies and tools emerging regularly, keeping professionals in this field engaged and challenged.

**Combining GenAI and Data Engineering:**

As both fields are closely related, combining GenAI and data engineering skills can open up even more opportunities. Some potential roles include:

1. **AI Data Engineer**: This role involves designing and building data systems that support AI and machine learning applications.
2. **Data Scientist with AI expertise**: This role requires expertise in both data science and AI, enabling professionals to develop and deploy AI models that drive business decisions.
3. **AI Engineering Manager**: This role involves overseeing AI-related projects and ensuring that data engineering and AI development align to meet business objectives.

In summary, GenAI and Data Engineering are exciting and in-demand career paths in 2026, with

In [14]:
response_etl=ask_llm("In 3 bullet points,explain how the Medallion Architecture"
                    "(Bronze,zSilver,Gold: layers)relates to ETL pipelines",
                    system_message="You are a senior data engineering instructor" "Be concise and practical")
print("Medallion+ETL connection")
print(response_etl)
print()
print("----Token explanation---")
print("Each word is roughly 1-2 tokens:")
print("The model above used approxiamtely",len(response_etl.split()),"tokens")
print(" llama-3.1-8b context window;8192 tokens~ 6000 words per conversation")

Medallion+ETL connection
Here are 3 bullet points explaining how the Medallion Architecture (Bronze, Silver, Gold layers) relates to ETL pipelines:

• **Bronze Layer (Raw Data Ingestion)**: In the Medallion Architecture, the Bronze layer represents the raw data ingestion process, where data is first collected from various sources and stored in its original form. This layer is equivalent to the ETL pipeline's **Source System** and **Staging Area**, where data is extracted and temporarily stored before being transformed and loaded into a more structured format.

• **Silver Layer (Data Processing and Standardization)**: The Silver layer is where data is processed, transformed, and standardized to meet the requirements of the organization. This layer is equivalent to the ETL pipeline's **Data Processing** stage, where data is transformed, aggregated, and formatted according to business rules and requirements. In the ETL pipeline, this stage would involve data quality checks, data cleansing, and data transformation.

• **Gold Layer (Data Warehousing and Business Intelligence)**: The Gold layer represents the data warehousing and business intelligence layer, where data is stored in a structured and organized format for business analysis and decision-making. This layer is equivalent to the ETL pipeline's **Data Loading** stage, where transformed data is loaded into a data warehouse or a data mart for business analysis and reporting. In the ETL pipeline, this stage would involve loading data into a target system, such as a data warehouse or a data mart, for business intelligence and reporting purposes.

----Token explanation---
Each word is roughly 1-2 tokens:
The model above used approxiamtely 238 tokens
 llama-3.1-8b context window;8192 tokens~ 6000 words per conversation

In [15]:
zero_shot_response=ask_llm(
    "Extract the city name from this address: "
    "456 Brigade Road,Bangalore 560025,Karnataka,Idia"
)
print('zero-shot Result: ')
print(zero_shot_response)
print()

ambiguous_response=ask_llm("clean this data: ramesh Kumar,45000,mumbai")
print('Ambiguous zero-shot Result:')
print(ambiguous_response)
print()
print('problem:output format is unpredictable and not maachine parseable')

zero-shot Result:
The city name is: Bangalore

Ambiguous zero-shot Result:
It appears the data is in the format of a list with three elements per record, separated by commas.

To clean the data, I will assume that each record is a person's name followed by their salary and location. However, the data could use some cleaning and organization. Here is the cleaned data:

```python
# Define the data
data = ["ramesh Kumar,45000,mumbai"]

# Split the data into individual records
records = [record.split(",") for record in data]

# Print the cleaned data
for record in records:
    print(f"Name: {record[0].strip()}, Salary: {record[1].strip()}, Location: {record[2].strip()}")
```

When you run this script, it will output:

```
Name: ramesh Kumar, Salary: 45000, Location: mumbai
```

This cleaned data is now easier to read and work with.

problem:output format is unpredictable and not maachine parseable

In [16]:
few_shot_prompt="""
convert employee text to JSON.here are examples:
Input:RAMESH KUMAR,45000,mumbai
Output:{"name":"RAMESH KUMAR","salary":45000,"city":"mumbai"}

Input:Priya nair,52000,Delhi
Output:{"name":"Priya nair","salary":52000,"city":"Delhi"}
Now convert this:
Input:ANANYA DAS,38000,kolkata
Output:
"""
few_shot_response=ask_llm(few_shot_prompt)
print('few-shot Result:')
print(few_shot_response)
print()

try:
  parsed=json.loads(few_shot_response.strip())
  print("sucessfully parsed as JSON")
  print(f'Name: {parsed["name"]}')
  print(f'Salary: {parsed["salary"]}')
  print(f'City: {parsed["city"]}')
except json.JSONDecodeError:
  print('parsing failed --model added extra text')
  print('solution:add explicit instructions in the styles prompt')

few-shot Result:
Here's the conversion of the input to JSON:

Input: ANANYA DAS, 38000, kolkata

Output: {"name": "ANANYA DAS", "salary": 38000, "city": "kolkata"}

Here's a Python function to convert the employee text to JSON:

```python
import json

def convert_to_json(name, salary, city):
    employee = {
        "name": name,
        "salary": salary,
        "city": city
    }
    return json.dumps(employee)

# Example usage:
name = "ANANYA DAS"
salary = 38000
city = "kolkata"

output = convert_to_json(name, salary, city)
print(output)
```

When you run this function with the given inputs, it will print:

```json
{"name": "ANANYA DAS", "salary": 38000, "city": "kolkata"}
```

parsing failed --model added extra text
solution:add explicit instructions in the styles prompt

In [17]:
same_question="review this python code and identify any issues:\n"\
"df['revenue]=df['qty']*df['price']\n"\
"result=df.groupby('dept).sum()"

generic_response=ask_llm(same_question,temperature=0.2)
print('without role prompting: ')
print(generic_response[:300],'...')
print()

role_response=ask_llm(
    same_question,
    system_message="you are a senior data engineer with 18 yrs of prediction"
    "experience.review code critically for production readiness,"
    "data type issues,and potential failures at scale.",
    temperature=0.2
)
print('with role promting(senior data engieer): ')
print(role_response[:400],'...')
print()
print('notice: role prompting produces more technical,actionablr feedback')

without role prompting:
Here's a review of the provided Python code:

```python
# The code is missing a colon at the end of the line
df['revenue'] = df['qty'] * df['price']

# There's a missing closing parenthesis at the end of the line
result = df.groupby('dept').sum()
```

Here's the corrected code:

```python
df['revenu ...

with role promting(senior data engieer):
**Code Review**

The provided Python code appears to be a simplified example of data manipulation and aggregation. However, there are several issues that need to be addressed for production readiness:

### 1. Data Type Issues

The code does not specify the data types of the columns involved in the calculation. This can lead to unexpected behavior if the data types are not what you expect.

```pyth ...

notice: role prompting produces more technical,actionablr feedback

In [18]:
prompt="give me one creative name for a data analytics startup."

print('===Temperature Experiment===')
for temp in [0.0,0.5,1.0]:
  response=ask_llm(prompt,temperature=temp)
  print(f'temp={temp}: {response.strip()}')
  time.sleep(1)
print()
print('observation: ')
print( 'temperature=0.0->same or very similar answer every run (deterministic)')
print( 'temperature=0.5->some variation')
print( 'temperature=1.0 ->more creative/varied,sometimes surpricing')
print()
print('rule for data engineering tasks:use temperature=0.0 or 0.1')
print('you need CONSISTENT,PARSEABLE output -> not creative variation')

===Temperature Experiment===
temp=0.0: Here's a creative name for a data analytics startup:

**Nexa Insights**

"Nexa" suggests connection and linkages, implying the ability to connect disparate data points and provide valuable insights. This name conveys the idea of a startup that helps businesses navigate complex data landscapes and uncover hidden patterns and trends.
temp=0.5: Here's a creative name for a data analytics startup:

**Nexa Insights**

"Nx" comes from the word "nexus," meaning a connection or link between things. This represents the connection between data and insights, as well as the connections between different data points and systems. "a" is a nod to the word "analytics," and "Insights" clearly communicates the value proposition of the startup.
temp=1.0: Here's a creative name for a data analytics startup: **Nexixa**

"Nexixa" combines the word "nexus" (meaning connection or link) with a Latin-inspired suffix (-ixa), suggesting a cutting-edge approach to data analytics and insights. This name aims to convey the idea of seamlessly connecting data, technology, and decision-makers to drive meaningful business outcomes.

observation:
temperature=0.0->same or very similar answer every run (deterministic)
temperature=0.5->some variation
temperature=1.0 ->more creative/varied,sometimes surpricing

rule for data engineering tasks:use temperature=0.0 or 0.1
you need CONSISTENT,PARSEABLE output -> not creative variation

In [23]:
invoice_test="Invoice #2024-001 from TECHWORLD SOLUTIONS dated 15th January 2024.Amount:Rs.45,000 for Laptop"
weak_response=ask_llm(
    f'clean this invoice data: {invoice_text}',
    temperature=0.3
)
print('weak prompt output: ')
print(weak_response)
print()

try:
  json.loads(weak_response)
  print('PARSABLE: yes')

except:
  print('PARSABLE: no-canot load into dataframe')
print('\n'+'='*50+'\n')

strong_system="""You are a data extraction specialist for an accounting pipeline.
extract invoice data and return ONLY a valid JSON object.
do not include any explanations,preamble,or markdown formatting.
return only the json,nothing else.

JSON schema (use null for missing values):
{"invoice_id":string,"vendor_name":string(Title Case),"amount":number(no currency symbols),
"currency":string(default INR),
"invoice_date":string(YYYY-MM-DD),
"category":string(Electronics/Services/Accessories/other)}"""

strong_response=ask_llm(
    f"Extract from :{invoice_test}",
    system_message=strong_system,
    temperature=0.0 #Always 0 for structured data extraction
)
print('STONG PROMPT OUTPUT:')
print(strong_response)
print()
try:
  parsed=json.loads(strong_response.strip())
  print('PARSEABLE:Yes')
  print(f"Vendor:{parsed.get('vendor_name')}")
  print(f'Amount:{parsed.get('amount')}')
  print(f'Date :{parsed.get("invoice_date")}')
except json.JSONDecodeError:
  #Fallback extract JSON with re.Regex
  match=re.search(r'\{.*?\}',strong_response,re.Dotall)
  if match:
    parsed=json.loads(match.group())
    print('PARSEABLE:Yes (extracted with regex fallback)')
  else:
    print('PAREABLE :No -retry with stricter prompt')

weak prompt output:
Here's the cleaned invoice data:

**Invoice Details:**

- **Invoice Number:** 2024-001
- **Date:** 15th January 2024
- **Supplier:** Techworld Solutions
- **Amount:** ₹ 45,000
- **Description:** Laptop

**Note:** I've assumed the currency as Indian Rupees (₹) based on the amount provided. If the amount is in a different currency, please let me know.

PARSABLE: no-canot load into dataframe

==================================================

STONG PROMPT OUTPUT:
{"invoice_id":"2024-001","vendor_name":"Techworld Solutions","amount":45000,"currency":"INR","invoice_date":"2024-01-15","category":"Electronics"}

PARSEABLE:Yes
Vendor:Techworld Solutions
Amount:45000
Date :2024-01-15

#MINI PROJECT

GOAL:Convert 5 messy invoice strings into a clean,structured pandas dataframe using LLM.
this is a complete GenAI-powered ETL pipeline:

messy text->LLM->JSON->DataFrame->Analysis

In [25]:
#install required libraries and import libraries
#!pip install groq pandas
#import pandas as pd
#from groq import groq

In [26]:
#add api key
API_KEY = "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"

client = Groq(api_key=API_KEY)

In [34]:
invoices = [

    "Invoice#101 John bought 2 laptops for $800 each on 12/01/2025",

    "Bill No 202 | Customer: Alice | Product: Mobile | Qty=1 | Total=600 dollars",

    "INV-303 Mike ordered 5 headphones worth $50 each",

    "Receipt 404: Sarah purchased 3 keyboards amount 120 each",

    "Invoice 505 customer David bought 2 monitors total price 400"
]

In [35]:
def extract_invoice(invoice_text):

    prompt = f"""
    Extract invoice information from the text below.

    Return ONLY valid JSON.
    Do not add explanation.
    Do not use markdown.
    Do not write anything except JSON.

    Required fields:
    - invoice_id
    - customer_name
    - product
    - quantity
    - unit_price
    - total_price

    Invoice:
    {invoice_text}
    """

    response = client.chat.completions.create(

        model="llama-3.1-8b-instant",

        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content

In [36]:
#test on one invoice
result=extract_invoice(invoices[0])
print(result)

{
  "invoice_id": "101",
  "customer_name": "John",
  "product": "laptops",
  "quantity": 2,
  "unit_price": 800,
  "total_price": 1600
}

In [37]:
structured_data = []

for invoice in invoices:

    result = extract_invoice(invoice)

    print("\nRAW OUTPUT:")
    print(result)

    try:

        # clean markdown if exists
        cleaned_result = result.replace("```json", "") \
                               .replace("```", "") \
                               .strip()

        json_data = json.loads(cleaned_result)

        structured_data.append(json_data)

    except Exception as e:

        print("Error parsing:", invoice)
        print("Reason:", e)

RAW OUTPUT:
{"invoice_id":101,"customer_name":"John","product":"laptop","quantity":2,"unit_price":800,"total_price":1600}

RAW OUTPUT:
{"invoice_id": "202", "customer_name": "Alice", "product": "Mobile", "quantity": "1", "unit_price": "600", "total_price": "600"}

RAW OUTPUT:
{
  "invoice_id": "INV-303",
  "customer_name": "Mike",
  "product": "headphones",
  "quantity": 5,
  "unit_price": 50,
  "total_price": 250
}

RAW OUTPUT:
{
  "invoice_id": 404,
  "customer_name": "Sarah",
  "product": "keyboards",
  "quantity": 3,
  "unit_price": 120,
  "total_price": 360
}

RAW OUTPUT:
{
  "invoice_id": "505",
  "customer_name": "David",
  "product": "monitors",
  "quantity": "2",
  "unit_price": "200",
  "total_price": "400"
}

In [38]:
#check extracted data
structured_data

[{'invoice_id': 101,
  'customer_name': 'John',
  'product': 'laptop',
  'quantity': 2,
  'unit_price': 800,
  'total_price': 1600},
 {'invoice_id': '202',
  'customer_name': 'Alice',
  'product': 'Mobile',
  'quantity': '1',
  'unit_price': '600',
  'total_price': '600'},
 {'invoice_id': 'INV-303',
  'customer_name': 'Mike',
  'product': 'headphones',
  'quantity': 5,
  'unit_price': 50,
  'total_price': 250},
 {'invoice_id': 404,
  'customer_name': 'Sarah',
  'product': 'keyboards',
  'quantity': 3,
  'unit_price': 120,
  'total_price': 360},
 {'invoice_id': '505',
  'customer_name': 'David',
  'product': 'monitors',
  'quantity': '2',
  'unit_price': '200',
  'total_price': '400'}]

In [39]:
#create dataframe
df=pd.DataFrame(structured_data)
df

  invoice_id customer_name     product quantity unit_price total_price
0        101          John      laptop        2        800        1600
1        202         Alice      Mobile        1        600         600
2    INV-303          Mike  headphones        5         50         250
3        404         Sarah   keyboards        3        120         360
4        505         David    monitors        2        200         400

In [40]:
#Data Cleaning
df["quantity"] = pd.to_numeric(df["quantity"])

df["unit_price"] = pd.to_numeric(df["unit_price"])

df["total_price"] = pd.to_numeric(df["total_price"])

In [41]:
#analysis
print("Total Revenue: ",df["total_price"].sum())

Total Revenue:  3210

In [44]:
#highest invoice
df.sort_values(by="total_price", ascending=False)

  invoice_id customer_name     product  quantity  unit_price  total_price
0        101          John      laptop         2         800         1600
1        202         Alice      Mobile         1         600          600
4        505         David    monitors         2         200          400
3        404         Sarah   keyboards         3         120          360
2    INV-303          Mike  headphones         5          50          250

In [45]:
#average invoice value
print("Average Invoice Value:", df["total_price"].mean())

Average Invoice Value: 642.0

In [46]:
#save csv
df.to_csv("clean_invoices.csv",index=False)